name: test_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  auto_route: ^10.1.2
  flutter_lints: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  import_sorter: ^4.6.0
  intl: 0.20.2
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  analyzer: ^7.4.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/core/presentation/assets/icons/
  fonts:
    - family: Nokwy
      fonts:
        - asset: lib/core/presentation/assets/fonts/Nokwy.otf
          weight: 400
    - family: Outfit
      fonts:
        - asset: lib/core/presentation/assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: lib/core/presentation/assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: lib/core/presentation/assets/fonts/Outfit-SemiBold.ttf
          weight: 600
import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - lib/core/presentation/l10n/*
