name: test_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  auto_route: ^10.1.2
  flutter_lints: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  import_sorter: ^4.6.0
  intl: 0.20.2
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  dotted_border: ^3.1.0
  group_button: ^5.3.4
  bloc: ^9.0.0
  image_picker: ^1.2.0
  collection: ^1.19.1
  flutter_secure_storage: ^4.2.1
  json_annotation: ^4.9.0
  share_plus: ^12.0.0
  graphql_flutter: ^5.2.1
  talker_flutter: ^5.0.1
  talker_http_logger: ^5.0.1
  http_interceptor: ^2.0.0
  http: ^1.5.0
  faker: ^2.2.0
  mime: ^2.0.0


dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  analyzer: ^7.4.0
  json_serializable: ^6.11.1
  graphql_codegen: ^2.0.0



flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/core/assets/icons/
  fonts:
    - family: Nokwy
      fonts:
        - asset: lib/core/assets/fonts/Nokwy.otf
          weight: 400
    - family: Outfit
      fonts:
        - asset: lib/core/assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: lib/core/assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: lib/core/assets/fonts/Outfit-SemiBold.ttf
          weight: 600
import_sorter:
  emojis: false
  comments: false
  ignored_files:
  - lib/core/l10n/*
  - lib/core/data/data_source/remote/graphql/*
  - lib/core/routing/*



